# Generated by Django 3.2.5 on 2021-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='esal',
            field=models.FloatField(),
        ),
    ]
